java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player java -cp java_example Migrate
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player java -cp java_example Migrate
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player java -cp java_example Migrate
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player java -cp java_example Migrate
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player java -cp java_example Migrate
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python python_example\gather.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python python_example\gather.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python python_example\gather.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python python_example\gather.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python python_example\gather.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python greedy.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python greedy.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python greedy.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python greedy.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python greedy.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python robber.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python robber.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python robber.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python robber.py
java -jar coercion.jar -player pipe 2 python enhancedRobber.py -player pipe 2 python robber.py
